# Generated by Django 5.1.2 on 2024-12-23 09:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FoundItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.CharField(blank=True, default='', max_length=10, unique=True)),
                ('item_name', models.CharField(max_length=100)),
                ('item_type', models.CharField(default='Found', max_length=10)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('electronics', 'Electronics'), ('clothing', 'Clothing'), ('accessories', 'Accessories'), ('documents', 'Documents'), ('keys', 'Keys'), ('books_stationary', 'Books & Stationary'), ('bags_luggage', 'Bags & Luggage'), ('sporting_goods', 'Sporting Goods'), ('toys_games', 'Toys & Games'), ('money', 'Money')], max_length=50)),
                ('date_found', models.DateField()),
                ('location_found', models.CharField(max_length=100)),
                ('contact_information', models.CharField(max_length=100)),
                ('found_by', models.CharField(blank=True, max_length=100, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='found_items/')),
                ('is_claimed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='LostItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.CharField(blank=True, default='', max_length=10, unique=True)),
                ('item_name', models.CharField(max_length=100)),
                ('item_type', models.CharField(default='Lost', max_length=10)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('electronics', 'Electronics'), ('clothing', 'Clothing'), ('accessories', 'Accessories'), ('documents', 'Documents'), ('keys', 'Keys'), ('books_stationary', 'Books & Stationary'), ('bags_luggage', 'Bags & Luggage'), ('sporting_goods', 'Sporting Goods'), ('toys_games', 'Toys & Games'), ('money', 'Money')], max_length=50)),
                ('date_lost', models.DateField()),
                ('location_lost', models.CharField(max_length=100)),
                ('contact_information', models.CharField(max_length=100)),
                ('lost_by', models.CharField(blank=True, max_length=100, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='lost_items/')),
                ('is_claimed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Address', models.CharField(blank=True, max_length=255, null=True)),
                ('Contact_Number', models.CharField(blank=True, max_length=15, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='F2FClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claimed_at', models.DateTimeField(auto_now_add=True)),
                ('appointment_required', models.BooleanField(default=False)),
                ('claimed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('found_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Appli.founditem')),
                ('lost_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Appli.lostitem')),
            ],
        ),
        migrations.CreateModel(
            name='OnlineClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claimed_at', models.DateTimeField(auto_now_add=True)),
                ('appointment_date', models.DateTimeField()),
                ('is_confirmed', models.BooleanField(default=False)),
                ('claimed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('found_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Appli.founditem')),
                ('lost_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Appli.lostitem')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('middle_name', models.CharField(blank=True, max_length=30)),
                ('sex', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female')], max_length=10)),
                ('phone_number', models.CharField(max_length=15)),
                ('role', models.CharField(choices=[('User', 'User'), ('ADMIN', 'Admin')], default='User', max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Appli.school')),
            ],
        ),
        migrations.AddField(
            model_name='lostitem',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Appli.school'),
        ),
        migrations.CreateModel(
            name='HistoryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete')], max_length=10)),
                ('item_name', models.CharField(max_length=255)),
                ('performed_by', models.CharField(max_length=200, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('role', models.CharField(choices=[('User', 'User'), ('ADMIN', 'Admin')], max_length=10, null=True)),
                ('school', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Appli.school')),
            ],
        ),
        migrations.AddField(
            model_name='founditem',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Appli.school'),
        ),
    ]
